apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: skfm9bb9n-python
  janus-idp.io/tekton: skfm9bb9n-python
  backstage.io/kubernetes-id: skfm9bb9n-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: skfm9bb9n-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
